# docker.compose.yml
version: '3.4'

services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    networks:
      - dev_network

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dev_database_storage:/var/lib/mysql
    networks:
      - dev_network
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb

  phpmyadmin:
    image: phpmyadmin:5.1.1
    ports:
      - 8080:80
    networks:
      - dev_network
    environment:
      PMA_HOST: database

networks:
  dev_network:


volumes:
  dev_database_storage:
