# docker.compose.yml
version: '3.4'

services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    networks:
      - php_workshop_dev_network

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - php_workshop_mysql_storage:/var/lib/mysql
    networks:
      - php_workshop_dev_network
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: php_workshop

  phpmyadmin:
    image: phpmyadmin:5.1.1
    ports:
      - 8080:80
    networks:
      - php_workshop_dev_network
    environment:
      PMA_HOST: mysql

networks:
  php_workshop_dev_network:


volumes:
  php_workshop_mysql_storage:
